name: CI

on: [push, pull_request]

jobs:
  main:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        dc:
          - dmd-latest
          - dmd-2.099.1
          - ldc-latest
          - ldc-1.29.0
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Prepare compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ${{ matrix.dc }}

      - name: Run tests
        run: |
          dub test -b unittest-cov
          dub build -b ddox

      
        
